- hosts: localhost
  become: false
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Arch install
      when: ansible_facts['os_family'] == "Archlinux"
      include_tasks: tasks/00_arch_essentials.yml
    - name: Ubuntu install
      when: ansible_facts['os_family'] == "Debian"
      include_tasks: tasks/00_ubuntu_essentials.yml
    - name: MacOS install
      when: ansible_facts['os_family'] == "Darwin"
      include_tasks: tasks/00_macos_essentials.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/node.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/lsp.yml
