- hosts: localhost
  become: false
  vars:
    the_user: "{{ ansible_user_id }}"
  pre_tasks:
    - name: Update apt cache
      become: true
      tags:
        - zsh
        - node 
      apt:
        update_cache: true
  tasks:
    - include: tasks/essentials.yml
    - include: tasks/zsh.yml
    - include: tasks/node.yml
    - include: tasks/nvim.yml
    - include: tasks/dotfiles.yml
