- hosts: localhost
  become: false
  vars:
    the_user: "{{ ansible_user_id }}"
  pre_tasks:
    - name: Update apt cache
      become: true
      tags:
        - ubuntu
      apt:
        update_cache: true
    - name: Update pacman cache
      become: true
      ansible.builtin.command:
        cmd: "sudo pacman -Syu"
      tags:
        - arch 
  tasks:
    - name: Install rust
      yay: name=rust state=present
      tags:
        - arch
    - include: tasks/essentials_arch.yml
    - include: tasks/essentials_ubuntu.yml
    - include: tasks/zsh.yml
    - include: tasks/node.yml
    - include: tasks/nvim.yml
    - include: tasks/dotfiles.yml
    - include: tasks/lsp.yml
