- name: Installing stow
  become: true
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
    - ubuntu 
- name: Installing stow
  become: true
  pacman: name=stow
  tags:
    - install
    - dotfiles
    - stow
    - arch 
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/ikerUrle/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Make install executable
  shell: chmod u+x $HOME/.dotfiles/install 
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
  tags:
    - install
    - dotfiles
    - stow
