- name: Install prettierd
  npm: 
    name: "@fsouza/prettierd"
    global: true
  become: true
  tags:
    - node
- name: Install eslint_d 
  npm: 
    name: eslint_d 
    global: true
  become: true
  tags:
    - node
