- name: neovim ppa (ppa:neovim-ppa/unstable)
  become: true
  apt_repository:
   repo: ppa:neovim-ppa/unstable
   state: present
   update_cache: True
  tags:
    - install
# - name: Get Packer
#   ansible.builtin.git:
#     repo: 'https://github.com/wbthomason/packer.nvim'
#     dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
#   tags:
#     - install
#     - neovim
- name: Install neovim
  become: true
  apt: 
    name: neovim
  tags:
    - install
    - neovim
