- name: Change shell to zsh for user "{{the_user}}"
  become: true
  user:
    name: "{{the_user}}"
    shell: /bin/zsh
  tags:
    - zsh
- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result
  tags:
    - zsh
- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result
  tags:
    - zsh

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists
  tags:
    - zsh

- name: Cloning  oh-my-zsh autosuggestions
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions
    dest=~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags:
    - zsh

- name: Deleting old ~/.zshrc
  ansible.builtin.command:
    cmd: "rm ~/.zshrc"
  when: stat_rc_result.stat.exists
  tags:
    - zsh
