- name: Install zsh
  apt: name=zsh
  become: true
  tags:
    - zsh
- name: Change shell to zsh for user "{{the_user}}"
  become: true
  user:
    name: "{{the_user}}"
    shell: /bin/zsh
  tags:
    - zsh
- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result
  tags:
    - zsh
- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result
  tags:
    - zsh

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists
  tags:
    - zsh

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: not stat_rc_result.stat.exists
  tags:
    - zsh
